"""phone_first_signup_nullable_identity_fields

Revision ID: 3cee33286dda
Revises: 45bfe2c8fef5
Create Date: 2026-09-17 09:56:37.353956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cee33286dda'
down_revision: Union[str, Sequence[str], None] = '45bfe2c8fef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    op.alter_column('users', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'national_id_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'national_id_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    # ### end Alembic commands ###
