"""data subject requests phase 8

Revision ID: 436d571ee7d4
Revises: da8348fec0b8
Create Date: 2026-09-16 10:13:56.251480

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '436d571ee7d4'
down_revision: str | Sequence[str] | None = 'da8348fec0b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_subject_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Enum('access', 'correction', 'deletion', name='data_subject_request_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'rejected', name='data_subject_request_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('actioned_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actioned_by_admin_id'], ['admin_users.id'], name=op.f('fk_data_subject_requests_actioned_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_data_subject_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_subject_requests'))
    )
    op.create_index(op.f('ix_data_subject_requests_user_id'), 'data_subject_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_subject_requests_user_id'), table_name='data_subject_requests')
    op.drop_table('data_subject_requests')
    # ### end Alembic commands ###
