"""ditsala meet phase 1 tables

Revision ID: 43bc6ded0da2
Revises: 436d571ee7d4
Create Date: 2026-09-16 11:39:23.984094

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43bc6ded0da2'
down_revision: str | Sequence[str] | None = '436d571ee7d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('host_user_id', sa.UUID(), nullable=False),
    sa.Column('livekit_room_name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meeting_type', sa.Enum('standard', 'webinar', 'classroom', 'interview', 'town_hall', 'conference', name='meeting_type', native_enum=False), server_default=sa.text("'standard'"), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'ended', 'cancelled', name='meeting_status', native_enum=False), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('scheduled_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('waiting_room_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], name=op.f('fk_meetings_host_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings')),
    sa.UniqueConstraint('livekit_room_name', name=op.f('uq_meetings_livekit_room_name'))
    )
    op.create_index(op.f('ix_meetings_host_user_id'), 'meetings', ['host_user_id'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_display_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('host', 'co_host', 'participant', name='meeting_participant_role', native_enum=False), server_default=sa.text("'participant'"), nullable=False),
    sa.Column('livekit_participant_identity', sa.String(length=128), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_participants_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meeting_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_participants'))
    )
    op.create_index(op.f('ix_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_user_id'), 'meeting_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_participants_user_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_meeting_id'), table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_meetings_host_user_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
