"""sender_key_per_recipient_device

Revision ID: 45bfe2c8fef5
Revises: c5b817982b0e
Create Date: 2026-09-17 02:23:32.081689

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '45bfe2c8fef5'
down_revision: str | Sequence[str] | None = 'c5b817982b0e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sender_keys', sa.Column('recipient_device_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_sender_keys_recipient_device_id'), 'sender_keys', ['recipient_device_id'], unique=False)
    op.create_unique_constraint('uq_sender_keys_conversation_device_recipient', 'sender_keys', ['conversation_id', 'device_id', 'recipient_device_id'])
    op.create_foreign_key(op.f('fk_sender_keys_recipient_device_id_devices'), 'sender_keys', 'devices', ['recipient_device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sender_keys_recipient_device_id_devices'), 'sender_keys', type_='foreignkey')
    op.drop_constraint('uq_sender_keys_conversation_device_recipient', 'sender_keys', type_='unique')
    op.drop_index(op.f('ix_sender_keys_recipient_device_id'), table_name='sender_keys')
    op.drop_column('sender_keys', 'recipient_device_id')
    # ### end Alembic commands ###
