"""ditsala_meet_phase_4_webinar

Revision ID: 4aba41f6eda6
Revises: b247733a7745
Create Date: 2026-09-17 00:06:07.934171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aba41f6eda6'
down_revision: Union[str, Sequence[str], None] = 'b247733a7745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_registrations',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_registrations_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meeting_registrations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_registrations')),
    sa.UniqueConstraint('meeting_id', 'email', name='uq_meeting_registrations_meeting_id_email')
    )
    op.create_index(op.f('ix_meeting_registrations_meeting_id'), 'meeting_registrations', ['meeting_id'], unique=False)
    op.add_column('meeting_participants', sa.Column('stage_status', sa.Enum('audience', 'on_stage', name='meeting_participant_stage_status', native_enum=False), server_default=sa.text("'on_stage'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_participants', 'stage_status')
    op.drop_index(op.f('ix_meeting_registrations_meeting_id'), table_name='meeting_registrations')
    op.drop_table('meeting_registrations')
    # ### end Alembic commands ###
