"""core data model (spec section 4)

Revision ID: 631a559a0977
Revises: 9ef27ff365ca
Create Date: 2026-09-15 01:44:36.719389

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '631a559a0977'
down_revision: str | Sequence[str] | None = '9ef27ff365ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_permissions',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_admin_permissions_name'))
    )
    op.create_table('admin_roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_admin_roles_name'))
    )
    op.create_table('audit_log',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('national_id_hash', sa.String(length=128), nullable=False),
    sa.Column('account_state', sa.Enum('pending_email', 'pending_phone', 'pending_kyc_document', 'pending_kyc_liveness', 'pending_next_of_kin', 'pending_code', 'active', 'manual_review', 'suspended', 'deactivated', 'banned', name='account_state', native_enum=False), server_default=sa.text("'pending_email'"), nullable=False),
    sa.Column('ditsala_code_hash', sa.String(length=256), nullable=True),
    sa.Column('code_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_code_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('national_id_hash', name=op.f('uq_users_national_id_hash'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('admin_role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['admin_permissions.id'], name=op.f('fk_admin_role_permissions_permission_id_admin_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], name=op.f('fk_admin_role_permissions_role_id_admin_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_admin_role_permissions_role_id'))
    )
    op.create_index(op.f('ix_admin_role_permissions_permission_id'), 'admin_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_admin_role_permissions_role_id'), 'admin_role_permissions', ['role_id'], unique=False)
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('mfa_enrolled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], name=op.f('fk_admin_users_role_id_admin_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_users_email'))
    )
    op.create_index(op.f('ix_admin_users_role_id'), 'admin_users', ['role_id'], unique=False)
    op.create_table('blocks',
    sa.Column('blocker_user_id', sa.UUID(), nullable=False),
    sa.Column('blocked_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], name=op.f('fk_blocks_blocked_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_user_id'], ['users.id'], name=op.f('fk_blocks_blocker_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocks')),
    sa.UniqueConstraint('blocker_user_id', 'blocked_user_id', name=op.f('uq_blocks_blocker_user_id'))
    )
    op.create_index(op.f('ix_blocks_blocked_user_id'), 'blocks', ['blocked_user_id'], unique=False)
    op.create_index(op.f('ix_blocks_blocker_user_id'), 'blocks', ['blocker_user_id'], unique=False)
    op.create_table('contact_requests',
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='contact_request_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('channel', sa.Enum('qr', 'invite_link', 'phone_match', name='contact_request_channel', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_contact_requests_from_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_contact_requests_to_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_requests'))
    )
    op.create_index(op.f('ix_contact_requests_from_user_id'), 'contact_requests', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_contact_requests_to_user_id'), 'contact_requests', ['to_user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('contact_user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('unverified', 'verified', 'trusted', 'blocked', name='contact_tier', native_enum=False), server_default=sa.text("'unverified'"), nullable=False),
    sa.Column('safety_number_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], name=op.f('fk_contacts_contact_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_contacts_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('owner_user_id', 'contact_user_id', name=op.f('uq_contacts_owner_user_id'))
    )
    op.create_index(op.f('ix_contacts_contact_user_id'), 'contacts', ['contact_user_id'], unique=False)
    op.create_index(op.f('ix_contacts_owner_user_id'), 'contacts', ['owner_user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('type', sa.Enum('direct', 'group', name='conversation_type', native_enum=False), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('disappearing_timer_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_conversations_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.Enum('ios', 'android', name='device_platform', native_enum=False), nullable=False),
    sa.Column('push_token', sa.String(length=256), nullable=True),
    sa.Column('signal_registration_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('email_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_ref', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=32), server_default=sa.text("'email'"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'expired', name='verification_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verifications'))
    )
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.create_table('invitations',
    sa.Column('inviter_user_id', sa.UUID(), nullable=False),
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'link', name='invitation_channel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('sent', 'redeemed', 'expired', name='invitation_status', native_enum=False), server_default=sa.text("'sent'"), nullable=False),
    sa.Column('redeemed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], name=op.f('fk_invitations_inviter_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['users.id'], name=op.f('fk_invitations_redeemed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations'))
    )
    op.create_index(op.f('ix_invitations_invite_code'), 'invitations', ['invite_code'], unique=True)
    op.create_index(op.f('ix_invitations_inviter_user_id'), 'invitations', ['inviter_user_id'], unique=False)
    op.create_table('kyc_documents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('sa_id', 'passport', name='kyc_document_type', native_enum=False), nullable=False),
    sa.Column('smile_id_job_id', sa.String(length=128), nullable=False),
    sa.Column('capture_method', sa.Enum('camera_live', name='kyc_capture_method', native_enum=False), server_default=sa.text("'camera_live'"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'passed', 'failed', 'manual_review', name='kyc_document_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_kyc_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_documents')),
    sa.UniqueConstraint('smile_id_job_id', name=op.f('uq_kyc_documents_smile_id_job_id'))
    )
    op.create_index(op.f('ix_kyc_documents_user_id'), 'kyc_documents', ['user_id'], unique=False)
    op.create_table('kyc_face_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('smile_id_job_id', sa.String(length=128), nullable=False),
    sa.Column('selfie_liveness_score', sa.Float(), nullable=True),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'passed', 'failed', name='kyc_face_verification_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_kyc_face_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_face_verifications')),
    sa.UniqueConstraint('smile_id_job_id', name=op.f('uq_kyc_face_verifications_smile_id_job_id'))
    )
    op.create_index(op.f('ix_kyc_face_verifications_user_id'), 'kyc_face_verifications', ['user_id'], unique=False)
    op.create_table('location_shares',
    sa.Column('sharer_user_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_location_shares_recipient_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sharer_user_id'], ['users.id'], name=op.f('fk_location_shares_sharer_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_shares'))
    )
    op.create_index(op.f('ix_location_shares_recipient_user_id'), 'location_shares', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_location_shares_sharer_user_id'), 'location_shares', ['sharer_user_id'], unique=False)
    op.create_table('next_of_kin',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('notified_on_sos', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_next_of_kin_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_next_of_kin'))
    )
    op.create_index(op.f('ix_next_of_kin_user_id'), 'next_of_kin', ['user_id'], unique=False)
    op.create_table('phone_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_ref', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=32), server_default=sa.text("'sms'"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'expired', name='verification_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_phone_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_verifications'))
    )
    op.create_index(op.f('ix_phone_verifications_user_id'), 'phone_verifications', ['user_id'], unique=False)
    op.create_table('sos_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_window_seconds', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('armed', 'cancelled', 'escalated', 'resolved', name='sos_event_status', native_enum=False), server_default=sa.text("'armed'"), nullable=False),
    sa.Column('last_known_location_ref', sa.String(length=256), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sos_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sos_events'))
    )
    op.create_index(op.f('ix_sos_events_user_id'), 'sos_events', ['user_id'], unique=False)
    op.create_table('account_recovery_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('initiated', 'liveness_passed', 'liveness_failed', 'next_of_kin_flagged', 'completed', 'aborted', name='account_recovery_status', native_enum=False), server_default=sa.text("'initiated'"), nullable=False),
    sa.Column('smile_id_job_id', sa.String(length=128), nullable=True),
    sa.Column('new_device_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['new_device_id'], ['devices.id'], name=op.f('fk_account_recovery_requests_new_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_recovery_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_recovery_requests'))
    )
    op.create_index(op.f('ix_account_recovery_requests_user_id'), 'account_recovery_requests', ['user_id'], unique=False)
    op.create_table('calls',
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('initiator_user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('voice', 'video', name='call_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ringing', 'active', 'ended', 'missed', 'declined', name='call_status', native_enum=False), server_default=sa.text("'ringing'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_calls_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['users.id'], name=op.f('fk_calls_initiator_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls'))
    )
    op.create_index(op.f('ix_calls_initiator_user_id'), 'calls', ['initiator_user_id'], unique=False)
    op.create_table('conversation_members',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('member', 'admin', name='conversation_member_role', native_enum=False), server_default=sa.text("'member'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_members_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_members'))
    )
    op.create_index(op.f('ix_conversation_members_conversation_id'), 'conversation_members', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_members_user_id'), 'conversation_members', ['user_id'], unique=False)
    op.create_table('identity_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('public_identity_key', sa.LargeBinary(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_identity_keys_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_identity_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_keys')),
    sa.UniqueConstraint('device_id', name=op.f('uq_identity_keys_device_id'))
    )
    op.create_index(op.f('ix_identity_keys_user_id'), 'identity_keys', ['user_id'], unique=False)
    op.create_table('location_access_log',
    sa.Column('location_share_id', sa.UUID(), nullable=False),
    sa.Column('accessed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accessed_by_user_id'], ['users.id'], name=op.f('fk_location_access_log_accessed_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_share_id'], ['location_shares.id'], name=op.f('fk_location_access_log_location_share_id_location_shares'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_access_log'))
    )
    op.create_index(op.f('ix_location_access_log_location_share_id'), 'location_access_log', ['location_share_id'], unique=False)
    op.create_table('location_pings',
    sa.Column('location_share_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_share_id'], ['location_shares.id'], name=op.f('fk_location_pings_location_share_id_location_shares'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_pings'))
    )
    op.create_index(op.f('ix_location_pings_location_share_id'), 'location_pings', ['location_share_id'], unique=False)
    op.create_index(op.f('ix_location_pings_recorded_at'), 'location_pings', ['recorded_at'], unique=False)
    op.create_table('login_attempts',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('ip_hash', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.Enum('code', 'face_liveness', name='login_attempt_stage', native_enum=False), nullable=False),
    sa.Column('outcome', sa.Enum('success', 'failure', name='login_attempt_outcome', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_login_attempts_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_attempts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_device_id', sa.UUID(), nullable=True),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'media', 'voice_note', 'reaction', 'system', name='message_content_type', native_enum=False), nullable=False),
    sa.Column('client_message_id', sa.String(length=128), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_device_id'], ['devices.id'], name=op.f('fk_messages_sender_device_id_devices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('client_message_id', name=op.f('uq_messages_client_message_id'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('one_time_prekeys',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_one_time_prekeys_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_one_time_prekeys'))
    )
    op.create_index(op.f('ix_one_time_prekeys_device_id'), 'one_time_prekeys', ['device_id'], unique=False)
    op.create_table('push_tokens',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('expo_push_token', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_push_tokens_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_tokens')),
    sa.UniqueConstraint('expo_push_token', name=op.f('uq_push_tokens_expo_push_token'))
    )
    op.create_index(op.f('ix_push_tokens_device_id'), 'push_tokens', ['device_id'], unique=False)
    op.create_table('reports',
    sa.Column('reporter_user_id', sa.UUID(), nullable=False),
    sa.Column('reported_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('context_ref', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('open', 'reviewed', 'actioned', name='report_status', native_enum=False), server_default=sa.text("'open'"), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], name=op.f('fk_reports_reported_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], name=op.f('fk_reports_reporter_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admin_users.id'], name=op.f('fk_reports_reviewed_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_user_id'), 'reports', ['reporter_user_id'], unique=False)
    op.create_table('sender_keys',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('distribution_message_ref', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_sender_keys_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sender_keys_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sender_keys'))
    )
    op.create_index(op.f('ix_sender_keys_conversation_id'), 'sender_keys', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sender_keys_device_id'), 'sender_keys', ['device_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=256), nullable=False),
    sa.Column('access_token_family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sessions_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_access_token_family_id'), 'sessions', ['access_token_family_id'], unique=False)
    op.create_index(op.f('ix_sessions_device_id'), 'sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('signed_prekeys',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('signature', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_signed_prekeys_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signed_prekeys'))
    )
    op.create_index(op.f('ix_signed_prekeys_device_id'), 'signed_prekeys', ['device_id'], unique=False)
    op.create_table('sos_notifications',
    sa.Column('sos_event_id', sa.UUID(), nullable=False),
    sa.Column('notified_user_id', sa.UUID(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.Enum('push', 'sms', name='sos_notification_channel', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notified_user_id'], ['users.id'], name=op.f('fk_sos_notifications_notified_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sos_event_id'], ['sos_events.id'], name=op.f('fk_sos_notifications_sos_event_id_sos_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sos_notifications'))
    )
    op.create_index(op.f('ix_sos_notifications_sos_event_id'), 'sos_notifications', ['sos_event_id'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admin_users.id'], name=op.f('fk_system_config_updated_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_config'))
    )
    op.create_table('call_participants',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ice_relay_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_participants_call_id_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_call_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_participants'))
    )
    op.create_index(op.f('ix_call_participants_call_id'), 'call_participants', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_participants_user_id'), 'call_participants', ['user_id'], unique=False)
    op.create_table('media_objects',
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('encrypted_size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('client_side_encrypted', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_media_objects_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_objects'))
    )
    op.create_index(op.f('ix_media_objects_message_id'), 'media_objects', ['message_id'], unique=False)
    op.create_table('message_receipts',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('delivered', 'read', name='message_receipt_status', native_enum=False), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_receipts_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_receipts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_receipts'))
    )
    op.create_index(op.f('ix_message_receipts_message_id'), 'message_receipts', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_receipts_user_id'), 'message_receipts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_receipts_user_id'), table_name='message_receipts')
    op.drop_index(op.f('ix_message_receipts_message_id'), table_name='message_receipts')
    op.drop_table('message_receipts')
    op.drop_index(op.f('ix_media_objects_message_id'), table_name='media_objects')
    op.drop_table('media_objects')
    op.drop_index(op.f('ix_call_participants_user_id'), table_name='call_participants')
    op.drop_index(op.f('ix_call_participants_call_id'), table_name='call_participants')
    op.drop_table('call_participants')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_sos_notifications_sos_event_id'), table_name='sos_notifications')
    op.drop_table('sos_notifications')
    op.drop_index(op.f('ix_signed_prekeys_device_id'), table_name='signed_prekeys')
    op.drop_table('signed_prekeys')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_device_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_access_token_family_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_sender_keys_device_id'), table_name='sender_keys')
    op.drop_index(op.f('ix_sender_keys_conversation_id'), table_name='sender_keys')
    op.drop_table('sender_keys')
    op.drop_index(op.f('ix_reports_reporter_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_push_tokens_device_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_index(op.f('ix_one_time_prekeys_device_id'), table_name='one_time_prekeys')
    op.drop_table('one_time_prekeys')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_location_pings_recorded_at'), table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_location_share_id'), table_name='location_pings')
    op.drop_table('location_pings')
    op.drop_index(op.f('ix_location_access_log_location_share_id'), table_name='location_access_log')
    op.drop_table('location_access_log')
    op.drop_index(op.f('ix_identity_keys_user_id'), table_name='identity_keys')
    op.drop_table('identity_keys')
    op.drop_index(op.f('ix_conversation_members_user_id'), table_name='conversation_members')
    op.drop_index(op.f('ix_conversation_members_conversation_id'), table_name='conversation_members')
    op.drop_table('conversation_members')
    op.drop_index(op.f('ix_calls_initiator_user_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_account_recovery_requests_user_id'), table_name='account_recovery_requests')
    op.drop_table('account_recovery_requests')
    op.drop_index(op.f('ix_sos_events_user_id'), table_name='sos_events')
    op.drop_table('sos_events')
    op.drop_index(op.f('ix_phone_verifications_user_id'), table_name='phone_verifications')
    op.drop_table('phone_verifications')
    op.drop_index(op.f('ix_next_of_kin_user_id'), table_name='next_of_kin')
    op.drop_table('next_of_kin')
    op.drop_index(op.f('ix_location_shares_sharer_user_id'), table_name='location_shares')
    op.drop_index(op.f('ix_location_shares_recipient_user_id'), table_name='location_shares')
    op.drop_table('location_shares')
    op.drop_index(op.f('ix_kyc_face_verifications_user_id'), table_name='kyc_face_verifications')
    op.drop_table('kyc_face_verifications')
    op.drop_index(op.f('ix_kyc_documents_user_id'), table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.drop_index(op.f('ix_invitations_inviter_user_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invite_code'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_contacts_owner_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_user_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_contact_requests_to_user_id'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_from_user_id'), table_name='contact_requests')
    op.drop_table('contact_requests')
    op.drop_index(op.f('ix_blocks_blocker_user_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_blocked_user_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_admin_users_role_id'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_role_permissions_role_id'), table_name='admin_role_permissions')
    op.drop_index(op.f('ix_admin_role_permissions_permission_id'), table_name='admin_role_permissions')
    op.drop_table('admin_role_permissions')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('admin_roles')
    op.drop_table('admin_permissions')
    # ### end Alembic commands ###
