"""invitations expires_at phase 5 circle

Revision ID: 6511f2a9f7f2
Revises: 7cb71e7570d4
Create Date: 2026-09-15 07:45:59.411365

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6511f2a9f7f2'
down_revision: str | Sequence[str] | None = '7cb71e7570d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'expires_at')
    # ### end Alembic commands ###
