"""add reply_to_message_id (phase 4 replies)

Revision ID: 7cb71e7570d4
Revises: 1bcfa1c65e5e
Create Date: 2026-09-15 07:03:24.674156

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7cb71e7570d4'
down_revision: str | Sequence[str] | None = '1bcfa1c65e5e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_messages_reply_to_message_id_messages'), 'messages', 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_messages_reply_to_message_id_messages'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_message_id')
    # ### end Alembic commands ###
