"""ditsala_meet_phase_2

Revision ID: 8731972a18e2
Revises: ee91b3f2d954
Create Date: 2026-09-16 22:44:51.342634

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8731972a18e2'
down_revision: str | Sequence[str] | None = 'ee91b3f2d954'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_recordings',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('egress_id', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('processing', 'ready', 'failed', name='meeting_recording_status', native_enum=False), server_default=sa.text("'processing'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_recordings_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_recordings')),
    sa.UniqueConstraint('egress_id', name=op.f('uq_meeting_recordings_egress_id'))
    )
    op.create_index(op.f('ix_meeting_recordings_meeting_id'), 'meeting_recordings', ['meeting_id'], unique=False)
    op.create_table('meeting_messages',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('sender_participant_id', sa.UUID(), nullable=False),
    sa.Column('recipient_participant_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_messages_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_participant_id'], ['meeting_participants.id'], name=op.f('fk_meeting_messages_recipient_participant_id_meeting_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_participant_id'], ['meeting_participants.id'], name=op.f('fk_meeting_messages_sender_participant_id_meeting_participants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_messages'))
    )
    op.create_index(op.f('ix_meeting_messages_meeting_id'), 'meeting_messages', ['meeting_id'], unique=False)
    op.create_table('meeting_polls',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('created_by_participant_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_participant_id'], ['meeting_participants.id'], name=op.f('fk_meeting_polls_created_by_participant_id_meeting_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_polls_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_polls'))
    )
    op.create_index(op.f('ix_meeting_polls_meeting_id'), 'meeting_polls', ['meeting_id'], unique=False)
    op.create_table('meeting_questions',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('asked_by_participant_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('upvote_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('open', 'answered', 'dismissed', name='meeting_question_status', native_enum=False), server_default=sa.text("'open'"), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asked_by_participant_id'], ['meeting_participants.id'], name=op.f('fk_meeting_questions_asked_by_participant_id_meeting_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_questions_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_questions'))
    )
    op.create_index(op.f('ix_meeting_questions_meeting_id'), 'meeting_questions', ['meeting_id'], unique=False)
    op.create_table('meeting_poll_votes',
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('voter_participant_id', sa.UUID(), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['meeting_polls.id'], name=op.f('fk_meeting_poll_votes_poll_id_meeting_polls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_participant_id'], ['meeting_participants.id'], name=op.f('fk_meeting_poll_votes_voter_participant_id_meeting_participants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_poll_votes'))
    )
    op.create_index(op.f('ix_meeting_poll_votes_poll_id'), 'meeting_poll_votes', ['poll_id'], unique=False)
    op.add_column('meeting_participants', sa.Column('admission_status', sa.Enum('waiting', 'admitted', 'removed', name='meeting_participant_admission_status', native_enum=False), server_default=sa.text("'admitted'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_participants', 'admission_status')
    op.drop_index(op.f('ix_meeting_poll_votes_poll_id'), table_name='meeting_poll_votes')
    op.drop_table('meeting_poll_votes')
    op.drop_index(op.f('ix_meeting_questions_meeting_id'), table_name='meeting_questions')
    op.drop_table('meeting_questions')
    op.drop_index(op.f('ix_meeting_polls_meeting_id'), table_name='meeting_polls')
    op.drop_table('meeting_polls')
    op.drop_index(op.f('ix_meeting_messages_meeting_id'), table_name='meeting_messages')
    op.drop_table('meeting_messages')
    op.drop_index(op.f('ix_meeting_recordings_meeting_id'), table_name='meeting_recordings')
    op.drop_table('meeting_recordings')
    # ### end Alembic commands ###
