"""account deletion cascade fields phase 8

Revision ID: 88ffd866f54a
Revises: f98829234cbf
Create Date: 2026-09-16 08:57:35.438313

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88ffd866f54a'
down_revision: str | Sequence[str] | None = 'f98829234cbf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('hard_delete_after', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hard_delete_after')
    op.drop_column('users', 'deactivated_at')
    # ### end Alembic commands ###
