"""admin mfa secret phase 7

Revision ID: ac7e962fd9db
Revises: 6511f2a9f7f2
Create Date: 2026-09-16 01:44:35.097819

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac7e962fd9db'
down_revision: str | Sequence[str] | None = '6511f2a9f7f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('mfa_secret', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'mfa_secret')
    # ### end Alembic commands ###
