"""ditsala_meet_ai_pipeline

Revision ID: b247733a7745
Revises: e4f85b2192ae
Create Date: 2026-09-16 23:30:18.851871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b247733a7745'
down_revision: Union[str, Sequence[str], None] = 'e4f85b2192ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_ai_notes',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('summary', 'decision', 'action_item', 'question', 'topic', name='meeting_ai_note_kind', native_enum=False), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('edited_by_participant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_participant_id'], ['meeting_participants.id'], name=op.f('fk_meeting_ai_notes_edited_by_participant_id_meeting_participants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_ai_notes_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_ai_notes'))
    )
    op.create_index(op.f('ix_meeting_ai_notes_meeting_id'), 'meeting_ai_notes', ['meeting_id'], unique=False)
    op.create_table('meeting_transcripts',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('speaker_participant_id', sa.UUID(), nullable=True),
    sa.Column('text_segment', sa.String(length=8000), nullable=False),
    sa.Column('started_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('ended_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text_segment)", persisted=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_transcripts_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_participant_id'], ['meeting_participants.id'], name=op.f('fk_meeting_transcripts_speaker_participant_id_meeting_participants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_transcripts'))
    )
    op.create_index(op.f('ix_meeting_transcripts_meeting_id'), 'meeting_transcripts', ['meeting_id'], unique=False)
    op.add_column('meetings', sa.Column('title_search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', title)", persisted=True), nullable=False))
    # ### end Alembic commands ###

    # GIN indexes for the two generated tsvector columns above — plain
    # btree (what create_index would default to) can't serve a `@@`
    # tsquery match at all, so §18 search needs these explicitly.
    op.create_index(
        'ix_meeting_transcripts_search_vector',
        'meeting_transcripts',
        ['search_vector'],
        postgresql_using='gin',
    )
    op.create_index(
        'ix_meetings_title_search', 'meetings', ['title_search'], postgresql_using='gin'
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_meetings_title_search', table_name='meetings')
    op.drop_index('ix_meeting_transcripts_search_vector', table_name='meeting_transcripts')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'title_search')
    op.drop_index(op.f('ix_meeting_transcripts_meeting_id'), table_name='meeting_transcripts')
    op.drop_table('meeting_transcripts')
    op.drop_index(op.f('ix_meeting_ai_notes_meeting_id'), table_name='meeting_ai_notes')
    op.drop_table('meeting_ai_notes')
    # ### end Alembic commands ###
