"""messaging_avatar_and_group_titles

Revision ID: c5b817982b0e
Revises: 4aba41f6eda6
Create Date: 2026-09-17 01:53:47.315158

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5b817982b0e'
down_revision: str | Sequence[str] | None = '4aba41f6eda6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('avatar_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_key')
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
