"""recovery request verification flags phase 8

Revision ID: da8348fec0b8
Revises: 88ffd866f54a
Create Date: 2026-09-16 09:05:42.799342

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'da8348fec0b8'
down_revision: str | Sequence[str] | None = '88ffd866f54a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'account_recovery_requests',
        sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    op.add_column(
        'account_recovery_requests',
        sa.Column('phone_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_recovery_requests', 'phone_verified')
    op.drop_column('account_recovery_requests', 'email_verified')
    # ### end Alembic commands ###
