"""ditsala_meet_breakout_rooms

Revision ID: e4f85b2192ae
Revises: 8731972a18e2
Create Date: 2026-09-16 22:55:42.376692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f85b2192ae'
down_revision: Union[str, Sequence[str], None] = '8731972a18e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breakout_rooms',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('livekit_room_name', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_breakout_rooms_meeting_id_meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breakout_rooms')),
    sa.UniqueConstraint('livekit_room_name', name=op.f('uq_breakout_rooms_livekit_room_name'))
    )
    op.create_index(op.f('ix_breakout_rooms_meeting_id'), 'breakout_rooms', ['meeting_id'], unique=False)
    op.create_table('breakout_room_participants',
    sa.Column('breakout_room_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['breakout_room_id'], ['breakout_rooms.id'], name=op.f('fk_breakout_room_participants_breakout_room_id_breakout_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['meeting_participants.id'], name=op.f('fk_breakout_room_participants_participant_id_meeting_participants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breakout_room_participants'))
    )
    op.create_index(op.f('ix_breakout_room_participants_breakout_room_id'), 'breakout_room_participants', ['breakout_room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_breakout_room_participants_breakout_room_id'), table_name='breakout_room_participants')
    op.drop_table('breakout_room_participants')
    op.drop_index(op.f('ix_breakout_rooms_meeting_id'), table_name='breakout_rooms')
    op.drop_table('breakout_rooms')
    # ### end Alembic commands ###
