"""vip tier split phase 8

Revision ID: ee91b3f2d954
Revises: 7a3f2e9c1b4d
Create Date: 2026-09-16 14:39:28.069435

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee91b3f2d954'
down_revision: str | Sequence[str] | None = '7a3f2e9c1b4d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vip_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'awaiting_kyc', 'active', 'cancelled', 'expired', 'failed', name='vip_subscription_status', native_enum=False), server_default=sa.text("'pending_payment'"), nullable=False),
    sa.Column('payment_provider', sa.String(length=32), server_default=sa.text("'stitch'"), nullable=False),
    sa.Column('external_payment_reference', sa.String(length=128), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vip_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vip_subscriptions')),
    sa.UniqueConstraint('external_payment_reference', name=op.f('uq_vip_subscriptions_external_payment_reference'))
    )
    op.create_index(op.f('ix_vip_subscriptions_user_id'), 'vip_subscriptions', ['user_id'], unique=False)
    op.add_column('kyc_documents', sa.Column('purpose', sa.Enum('onboarding', 'vip_upgrade', name='kyc_purpose', native_enum=False), server_default=sa.text("'onboarding'"), nullable=False))
    op.add_column('kyc_face_verifications', sa.Column('purpose', sa.Enum('onboarding', 'vip_upgrade', name='kyc_purpose', native_enum=False), server_default=sa.text("'onboarding'"), nullable=False))
    op.add_column('users', sa.Column('account_tier', sa.Enum('normal', 'vip', name='account_tier', native_enum=False), server_default=sa.text("'normal'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_tier')
    op.drop_column('kyc_face_verifications', 'purpose')
    op.drop_column('kyc_documents', 'purpose')
    op.drop_index(op.f('ix_vip_subscriptions_user_id'), table_name='vip_subscriptions')
    op.drop_table('vip_subscriptions')
    # ### end Alembic commands ###
